# Site settings
title: Jekyll Basics
email: info@wiredcraft.com
description: "A boilerplate set up to create a bilingual Jekyll website."
keywords:
- Jekyll

# URL
url: "https://wiredcraft.github.io/jekyll-basics"
baseurl: ""

# Google tracking (Analytics and Google Tag Manager)
# google_tag_manager: GTM-XXXXXX
# google_analytics: UA-XXXXXXX-X

# SEO
twitter:
  username: wiredcraft
logo:

# Build settings
exclude: ['README.md', 'Makefile']

# Collections
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      class: post
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
      class: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      class: page

# Plugins
gems:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-seo-tag

# Multiligual
lang:
  - en
  - fr
  - zh
